# Basic tag
kind: Tag
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-tag-basic
  namespace: krateo-system
spec:
  widgetData:
    label: "stable"
---
# Colored tag
kind: Tag
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-tag-color
  namespace: krateo-system
spec:
  widgetData:
    color: "green"
    label: "production"
