# Basic QR code
kind: QRCode
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-qrcode-basic
  namespace: krateo-system
spec:
  widgetData:
    value: "https://krateo.io"
---
# Sized QR code
kind: QRCode
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: example-qrcode-sized
  namespace: krateo-system
spec:
  widgetData:
    size: 200
    value: "https://krateo.io"
