name: release-pullrequest

on:
  pull_request:
    branches:
      - main

jobs:
  lint-docs:
    uses: krateo-platformops/.github/.github/workflows/lint-docs.yaml@main
  build:
    uses: krateo-platformops/.github/.github/workflows/component-image-build.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      modules: '[{"mod":"frontend","context":"ui"}]'
      push: false
      build_args: |
        VERSION=${{ github.ref_name }}
        APP_BUILD=${{ github.sha }}
  crds:
    name: Generate crds
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Install krateoctl v0.8.9
        run: curl -sL https://raw.githubusercontent.com/krateoplatformops/krateoctl/main/install.sh 0.8.9 | bash

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tsx, chalk
        run: |
          npm install tsx chalk

      - name: Generate crds
        run: |
          npm run generate-crds

      - name: List files in /scripts/krateoctl-output
        run: |
          ls -la ./scripts/krateoctl-output

      - name: Upload .yaml files from /scripts/krateoctl-output
        uses: actions/upload-artifact@v4
        with:
          name: frontend-crds-yaml-files
          path: ${{ github.workspace }}/scripts/krateoctl-output/*.yaml
